const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage();
  await page.goto('https://ndosisimplifiedautomation.vercel.app/');
  await page.waitForTimeout(2000);
  await page.click('button.user-pill');
  await page.waitForTimeout(1000);
  await page.fill('#login-email', 'admin@gmail.com');
  await page.fill('#login-password', '@12345678');
  await page.click('button#login-submit');
  await page.waitForTimeout(4000);
  await page.click('button.user-pill');
  await page.waitForTimeout(2000);
  await page.click('button:has-text("Admin Panel")');
  await page.waitForTimeout(4000);
  await page.click('button:has-text("🎓Enrollments")');
  await page.waitForTimeout(4000);
  await page.click('button:has-text("+ Enroll User")');
  await page.waitForTimeout(2000);
  await page.selectOption('form:has(button[type="submit"]:has-text("Enroll User")) select[required]', { label: 'My Dummy Course' });
  await page.click('form:has(button[type="submit"]:has-text("Enroll User")) button[type="submit"]');
  await page.waitForTimeout(3000);
  const rows = await page.$$eval('table tbody tr', trs => trs.map(tr => tr.innerText.trim()));
  console.log('table rows count:', rows.length);
  console.log(JSON.stringify(rows.slice(0,20), null, 2));
  const emailElements = await page.$$eval('table tbody tr', trs => trs.map(tr => tr.querySelectorAll('*').length));
  console.log('row element counts:', emailElements.slice(0,20));
  await page.screenshot({ path: 'after-enroll-result.png', fullPage: true });
  await browser.close();
})();
